Repository 10aeat/10aeat_Backend, pull requests merged in 2024-06, with the labels that each got.

#134 [Feat] 마이페이지 동, 호수 조회 기능을 구현한다.
  src/main/java/com/final_10aeat/domain/member/controller/BuildingInfoController.java
  src/main/java/com/final_10aeat/domain/member/dto/response/BuildingInfoResponseDto.java
  src/main/java/com/final_10aeat/domain/member/entity/BuildingInfo.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
  src/main/java/com/final_10aeat/domain/member/repository/BuildingInfoRepository.java
  src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
  src/main/java/com/final_10aeat/domain/member/service/BuildingInfoService.java
Labels: 🛠️ feature

#140 [Feat] 내 동 호수 추가/삭제 및 내 정보 조회 기능구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member/mypage-api.adoc
  src/main/java/com/final_10aeat/domain/member/controller/BuildingInfoController.java
  src/main/java/com/final_10aeat/domain/member/controller/MyPageController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/BuildingInfoRequestDto.java
  src/main/java/com/final_10aeat/domain/member/dto/response/BuildingInfoResponseDto.java
  src/main/java/com/final_10aeat/domain/member/dto/response/MyBuildingInfoResponseDto.java
  src/main/java/com/final_10aeat/domain/member/dto/response/MyInfoResponseDto.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
  src/main/java/com/final_10aeat/domain/member/exception/BuildingInfoNotAssociatedException.java
  src/main/java/com/final_10aeat/domain/member/exception/BuildingInfoNotFound.java
  src/main/java/com/final_10aeat/domain/member/exception/DuplicateBuildingInfoException.java
  src/main/java/com/final_10aeat/domain/member/exception/MinBuildingInfoRequiredException.java
  src/main/java/com/final_10aeat/domain/member/repository/BuildingInfoRepository.java
  src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
  src/main/java/com/final_10aeat/domain/member/service/BuildingInfoService.java
  src/main/java/com/final_10aeat/domain/member/service/MyPageService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/member/docs/MyPageControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/save/unit/MyPageServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring

#142 [Feat] 내 댓글 조회, 내 저장 게시물 조회 구현 및 관련 로직 리팩토링
  src/docs/asciidoc/member/mypage-api.adoc
  src/main/java/com/final_10aeat/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/final_10aeat/domain/comment/repository/CommentRepository.java
  src/main/java/com/final_10aeat/domain/comment/service/CommentService.java
  src/main/java/com/final_10aeat/domain/member/controller/MyPageController.java
  src/main/java/com/final_10aeat/domain/member/dto/response/MyCommentsResponseDto.java
  src/main/java/com/final_10aeat/domain/member/dto/response/MySaveResponseDto.java
  src/main/java/com/final_10aeat/domain/member/service/MyPageService.java
  src/main/java/com/final_10aeat/domain/save/repository/ArticleSaveRepository.java
  src/main/java/com/final_10aeat/domain/save/service/ArticleSaveService.java
  src/test/java/com/final_10aeat/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/docs/MyPageControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/MyPageServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring

#138 [Feat] 법정점검의 스케쥴을 추가, 상태 변경, 수정, 삭제 할 수 있다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/managearticle/manageArticle-api.adoc
  src/docs/asciidoc/managearticle/manageSchedule-api.adoc
  src/main/java/com/final_10aeat/domain/manageArticle/controller/ManagerScheduleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/util/ScheduleConverter.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageSchedule.java
  src/main/java/com/final_10aeat/domain/manageArticle/exception/ScheduleMustHaveOneException.java
  src/main/java/com/final_10aeat/domain/manageArticle/exception/ScheduleNotFoundException.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageScheduleRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ManageScheduleService.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ManagerManageArticleService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ManagerManageArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ManagerScheduleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ManageScheduleServiceTest.java
Labels: 📕 document, 🛠️ feature

#149 [Refactor] 유지보수 게시글 조회 기능 리팩토링
  src/docs/asciidoc/repairarticle/get-repairarticle-api.adoc
  src/main/java/com/final_10aeat/domain/repairArticle/controller/GetRepairArticleController.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/ManagerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/OwnerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleFacade.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/GetRepairArticleDocsTest.java
Labels: 🚧 refactoring

#150 [Test] 법정점검 게시글 조회 기능 RestDocs & 테스트 코드
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/managearticle/get-manageArticle-api.adoc
  src/main/java/com/final_10aeat/domain/manageArticle/controller/ReadManageArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ReadManageArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ReadManageArticleServiceTest.java
Labels: 📕 document, 🚧 refactoring

#148 [Feat] 관리자의 이슈 수정, 삭제 기능을 구현한다.
  src/docs/asciidoc/articleissue/articleissue-api.adoc
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueController.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/request/IssueUpdateRequestDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueCheckService.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueService.java
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/IssueDeleteServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/IssueUpdateServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueCheckServiceTest.java
Labels: 🛠️ feature

#153 [Refactor] Spring Security 예외 처리를 한다
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtAuthenticationFilter.java
Labels: 🛠️ feature

#155 [Refactor] 요구사항에 맞춰 리팩토링
  src/docs/asciidoc/repairarticle/get-repairarticle-api.adoc
  src/main/java/com/final_10aeat/common/dto/CustomPageDto.java
  src/main/java/com/final_10aeat/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/final_10aeat/domain/comment/service/CommentService.java
  src/main/java/com/final_10aeat/domain/repairArticle/controller/GetRepairArticleController.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/OwnerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleFacade.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
  src/test/java/com/final_10aeat/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/GetRepairArticleDocsTest.java
Labels: 🚧 refactoring

#157 [fix] api 경로 추가
  src/docs/asciidoc/articleissue/issuecheck-api.adoc
  src/docs/asciidoc/index.adoc
Labels: 👷‍♂️ fix

#159 [Feat] 검색 기능을 구현한다.
  build.gradle
  src/main/java/com/final_10aeat/common/dto/util/PageConverter.java
  src/main/java/com/final_10aeat/controller/HealthCheckController.java
  src/main/java/com/final_10aeat/controller/SearchArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/controller/GetRepairArticleController.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
  src/main/java/com/final_10aeat/global/config/QueryDslConfig.java
  src/main/java/com/final_10aeat/usecase/SearchArticleUseCase.java
  src/test/java/com/final_10aeat/common/config/TestConfig.java
  src/test/java/com/final_10aeat/domain/manager/entity/ManagerEntityTest.java
Labels: 🛠️ feature

#160 [Feat] 이슈 히스토리 기능 구현
  src/docs/asciidoc/articleissue/get-issue-api.adoc
  src/docs/asciidoc/articleissue/issue-api.adoc
  src/docs/asciidoc/articleissue/issuecheck-api.adoc
  src/docs/asciidoc/articleissue/issuecheckdetail-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueCheckController.java
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueController.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/request/IssueUpdateRequestDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/response/ArticleIssueCheckResponseDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/response/IssueHistoryResponseDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/articleIssue/exception/InactiveIssueException.java
  src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueCheckService.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueService.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/ManagerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/OwnerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueCheckControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/IssueDeleteServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/IssueUpdateServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueDetailServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManagerArticleIssuePublishServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairArticleIssuePublishServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueDetailServiceTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ReadManageArticleServiceTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/GetRepairArticleDocsTest.java
Labels: 🛠️ feature, 🚧 refactoring

#163 [Test] 검색 기능에 대한 RestDocs & 테스트 코드
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/search/searcharticle-api.adoc
  src/test/java/com/final_10aeat/controller/SearchArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/docs/RestDocsSupport.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ManageArticleQueryDslRepositoryTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/unit/RepairArticleQueryDslRepositoryTest.java
Labels: 📕 document

#167 [Refactor] 전체적인 리팩토링 진행
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueCheckService.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueService.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/CreateCustomProgressRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/UpdateCustomProgressRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/CustomProgressResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/CustomProgress.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerRepairArticleService.java
  src/test/java/com/final_10aeat/domain/issue/unit/IssueUpdateServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueDetailServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueDetailServiceTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ReadManageArticleServiceTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/GetRepairArticleDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/ManagerRepairArticleDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/unit/ManagerRepairArticleServiceTest.java
Labels: 🚧 refactoring

#170 [fix] dev서버 데이터베이스 재생성
  src/main/resources/application-develop.yml
Labels: 👷‍♂️ fix

#171 [fix] dev서버 데이터베이스 재생성
  src/main/resources/application-develop.yml
Labels: 👷‍♂️ fix

#173 [refactor] 목록조회 파라미터 추가
  src/main/java/com/final_10aeat/domain/manageArticle/controller/ReadManageArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ReadManageArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ReadManageArticleServiceTest.java
Labels: 🚧 refactoring

#174 [Feat] S3를 연결한다
  .env.sample
  .github/workflows/ci-cd.yml
  Dockerfile
  build.gradle
  src/main/java/com/final_10aeat/common/exception/ImageConvertException.java
  src/main/java/com/final_10aeat/common/service/S3ImageUploader.java
  src/main/java/com/final_10aeat/global/config/S3Config.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: 🛠️ feature

#176 [Refactor] 요약 조회에서 총 게시글 수를 보여준다
  src/main/java/com/final_10aeat/domain/manageArticle/controller/ReadManageArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/response/ManageArticleSummaryResponse.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ReadManageArticleControllerDocsTest.java
Labels: 📕 document, 🚧 refactoring

#178 [Fix] 유지보수 상세조회, 요약조회 db에러 수정
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleService.java
Labels: 👷‍♂️ fix, 🐞 bug

#184 [Feat] 관리자 검색기능을 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/search/manager-searcharticle-api.adoc
  src/main/java/com/final_10aeat/controller/ManagerSearchArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/SearchManageArticleQuery.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/response/SearchManagersManageResponse.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/SearchRepairArticleQueryDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/response/SearchManagerRepairArticleResponseDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/usecase/SearchArticleUseCase.java
  src/test/java/com/final_10aeat/controller/ManagerSearchArticleControllerDocsTest.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#186 [fix] 쿼리dsl을 활용한 RepairArticleRepository 정렬 수정
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
Labels: 👷‍♂️ fix, 🐞 bug

#187 [Fix] RepairArticle 조회 쿼리를 이슈가 있는 게시물과 없는 게시물을 정확히 구분하여 페이징 처리
  src/main/java/com/final_10aeat/domain/repairArticle/repository/CustomProgressRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/GetRepairArticleService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerArticleListService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/OwnerArticleListService.java
Labels: 👷‍♂️ fix, 🚧 refactoring

#189 [Feat] 이미지 삭제 기능 구현 및 저장 로직 리팩토링
  src/docs/asciidoc/image/image-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/final_10aeat/Final10aeatApplication.java
  src/main/java/com/final_10aeat/common/scheduler/DeleteArticleImageScheduler.java
  src/main/java/com/final_10aeat/common/scheduler/config/SchedulerConfig.java
  src/main/java/com/final_10aeat/domain/repairArticle/controller/ManagerRepairArticleImageController.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/CreateRepairArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/UpdateRepairArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticleImage.java
  src/main/java/com/final_10aeat/domain/repairArticle/exception/ImageNotFoundException.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleImageRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerRepairArticleImageService.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerRepairArticleService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/ManagerRepairArticleDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/ManagerRepairArticleImageDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/unit/ManagerRepairArticleServiceTest.java
Labels: 🛠️ feature, 🚧 refactoring

#190 [Fix] 목록 조회시 가까운 일정이 상단에 위치하도록 검색한다
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/SearchManageArticleQuery.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleQueryDslRepositoryImpl.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ReadManageArticleService.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ReadManageArticleServiceTest.java
Labels: 👷‍♂️ fix, 🐞 bug
