Repository 10aeat/10aeat_Backend, pull requests merged in 2024-05, with the labels that each got.

#24 [Feat] 일관된 로깅을 위한 로그백 구성
  src/main/resources/logback-spring.xml
Labels: 🛠️ feature

#27 [Feat] Security 설정 및 Member 엔티티 골격 구성
  build.gradle
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberLoginRequestDto.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberRegisterRequestDto.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
  src/main/java/com/final_10aeat/domain/member/exception/MemberDuplicatedException.java
  src/main/java/com/final_10aeat/domain/member/exception/MemberNotExistException.java
  src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtTokenGenerator.java
  src/main/java/com/final_10aeat/global/security/jwt/exception/JwtNotFoundException.java
  src/main/java/com/final_10aeat/global/security/principal/MemberDetailsProvider.java
  src/main/java/com/final_10aeat/global/security/principal/MemberPrincipal.java
  src/main/java/com/final_10aeat/global/security/principal/MemberPrincipalService.java
  src/main/resources/application.yml
Labels: 📕 document, 🛠️ feature

#41 [Feature] application.yml을 분리한다 (local/ develop)
  .env.sample
  .github/workflows/ci-cd.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 👷‍♂️ fix, 🛠️ feature, 🚧 refactoring

#44 [Feat] Redis 추가
  .env.sample
  .github/workflows/ci-cd.yml
  Dockerfile
  build.gradle
  dockercompose-local.yml
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: 📕 document, 🛠️ feature

#49 [Feat] 도메인을 나누고 엔터티 클래스를 추가한다.
  src/main/java/com/final_10aeat/domain/admin/entity/Admin.java
  src/main/java/com/final_10aeat/domain/admin/entity/Office.java
  src/main/java/com/final_10aeat/domain/articleInteraction/entity/ArticleCheck.java
  src/main/java/com/final_10aeat/domain/articleInteraction/entity/ArticleSave.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssueCheck.java
  src/main/java/com/final_10aeat/domain/comment/entity/Comment.java
  src/main/java/com/final_10aeat/domain/comment/entity/CommentLike.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManagePeriod.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageSchedule.java
  src/main/java/com/final_10aeat/domain/member/entity/BuildingInfo.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
  src/main/java/com/final_10aeat/domain/member/entity/MemberRole.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/ArticleCategory.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/CustomProgress.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/Progress.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticleImage.java
Labels: 🛠️ feature

#55 [Refactor] 기획 변경 사항 엔터티에 반영
  src/main/java/com/final_10aeat/domain/comment/entity/CommentLike.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
Labels: 🚧 refactoring

#61 [Feature] Spring REST Docs 기본 세팅 및 이메일 로직 테스트 코드 추가
  build.gradle
  src/docs/asciidoc/email/email-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/final_10aeat/global/util/ResponseDTO.java
  src/test/java/com/final_10aeat/docs/CommonDocsController.java
  src/test/java/com/final_10aeat/docs/CommonDocsTest.java
  src/test/java/com/final_10aeat/docs/RestDocsSupport.java
  src/test/java/com/final_10aeat/domain/member/docs/EmailControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/LocalEmailServiceTest.java
Labels: 🛠️ feature

#64 [Refactor] 코드 리뷰 반영해 이메일 로직 리팩토링
  Dockerfile
  src/main/java/com/final_10aeat/domain/member/controller/EmailController.java
  src/main/java/com/final_10aeat/domain/member/exception/InvalidVerificationCodeException.java
  src/main/java/com/final_10aeat/domain/member/service/DevelopEmailService.java
  src/main/java/com/final_10aeat/domain/member/service/EmailUseCase.java
  src/main/java/com/final_10aeat/domain/member/service/LocalEmailService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/member/docs/EmailControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/LocalEmailServiceTest.java
Labels: 🚧 refactoring

#60 [Feature] 이메일 인증코드 전송, 검증 기능을 구현한다.
  Dockerfile
  build.gradle
  src/docs/asciidoc/email/email-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/final_10aeat/domain/member/controller/EmailController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/EmailRequestDto.java
  src/main/java/com/final_10aeat/domain/member/dto/request/EmailVerificationRequestDto.java
  src/main/java/com/final_10aeat/domain/member/dto/response/EmailVerificationResponseDto.java
  src/main/java/com/final_10aeat/domain/member/exception/EmailSendingException.java
  src/main/java/com/final_10aeat/domain/member/exception/EmailTemplateLoadException.java
  src/main/java/com/final_10aeat/domain/member/exception/InvalidVerificationCodeException.java
  src/main/java/com/final_10aeat/domain/member/exception/VerificationCodeExpiredException.java
  src/main/java/com/final_10aeat/domain/member/service/DevelopEmailService.java
  src/main/java/com/final_10aeat/domain/member/service/EmailUseCase.java
  src/main/java/com/final_10aeat/domain/member/service/LocalEmailService.java
  src/main/java/com/final_10aeat/global/config/EmailConfig.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/main/java/com/final_10aeat/global/util/ResponseDTO.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
  src/main/resources/templates/email_template.html
  src/test/java/com/final_10aeat/docs/CommonDocsController.java
  src/test/java/com/final_10aeat/docs/CommonDocsTest.java
  src/test/java/com/final_10aeat/docs/RestDocsSupport.java
  src/test/java/com/final_10aeat/domain/member/docs/EmailControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/LocalEmailServiceTest.java
Labels: 🛠️ feature

#65 [Hotfix] ci 테스트 실패문제 수정 (ver1)
  Dockerfile
  src/test/java/com/final_10aeat/Final10aeatApplicationTests.java
Labels: 👷‍♂️ fix, 🐞 bug

#69 [Refactor] 로그인을 구현한다
  build.gradle
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtTokenGenerator.java
  src/main/java/com/final_10aeat/global/security/principal/MemberPrincipal.java
Labels: 🚧 refactoring

#73 [Feat] 서버 상태를 확인 할 수 있다
  .github/workflows/ci-cd.yml
  src/main/java/com/final_10aeat/controller/HealthCheckController.java
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
Labels: 🛠️ feature

#80 [feat] 로그인 테스트 코드와 RestDocs를 구성한다
  src/docs/asciidoc/email/email-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/login/Member-api.adoc
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberLoginRequestDto.java
  src/test/java/com/final_10aeat/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/MemberServiceTest.java
Labels: 📕 document, 🛠️ feature, 🚧 refactoring

#83 [Feature] 관리자 회원가입, 로그인 기능을 구현한다.
  build.gradle
  src/docs/asciidoc/admin/admin-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
  src/main/java/com/final_10aeat/domain/admin/dto/request/CreateAdminRequestDto.java
  src/main/java/com/final_10aeat/domain/admin/entity/Office.java
  src/main/java/com/final_10aeat/domain/admin/exception/OfficeNotFoundException.java
  src/main/java/com/final_10aeat/domain/admin/repository/AdminRepository.java
  src/main/java/com/final_10aeat/domain/admin/repository/OfficeRepository.java
  src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
  src/main/java/com/final_10aeat/domain/member/exception/EmailDuplicatedException.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/global/config/AppConfig.java
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/admin/docs/AdminControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/admin/entity/AdminEntityTest.java
  src/test/java/com/final_10aeat/domain/admin/unit/AdminServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/MemberServiceTest.java
Labels: 🛠️ feature

#77 [Feature] 회원가입, 탈퇴를 구현한다.
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberRegisterRequestDto.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberWithdrawRequestDto.java
  src/main/java/com/final_10aeat/domain/member/entity/Member.java
  src/main/java/com/final_10aeat/domain/member/exception/DisagreementException.java
  src/main/java/com/final_10aeat/domain/member/exception/MemberMissMatchException.java
  src/main/java/com/final_10aeat/domain/member/repository/BuildingInfoRepository.java
  src/main/java/com/final_10aeat/domain/member/repository/MemberRepository.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/main/java/com/final_10aeat/global/security/principal/MemberDetailsProvider.java
  src/test/java/com/final_10aeat/domain/member/unit/MemberServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/RegisterServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/WithdrawServiceTest.java
Labels: 🛠️ feature

#87 [Document] 회원 가입과 탈퇴의 API 문서를 작성한다.
  src/docs/asciidoc/member/member-api.adoc
  src/test/java/com/final_10aeat/domain/member/docs/MemberControllerDocsTest.java
Labels: 📕 document

#95 [Feature] 유지보수 게시글 생성, 삭제, 수정을 구현한다.
  src/main/java/com/final_10aeat/common/exception/UnauthorizedAccessException.java
  src/main/java/com/final_10aeat/common/scheduler/DeleteRepairArticleScheduler.java
  src/main/java/com/final_10aeat/common/scheduler/config/SchedulerConfig.java
  src/main/java/com/final_10aeat/domain/repairArticle/controller/ManagerRepairArticleController.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/CreateRepairArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/UpdateRepairArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/exception/ArticleAlreadyDeletedException.java
  src/main/java/com/final_10aeat/domain/repairArticle/exception/ArticleNotFoundException.java
  src/main/java/com/final_10aeat/domain/repairArticle/exception/ManagerNotFoundException.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/RepairArticleRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/RepairArticleService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/repairArticle/unit/DeleteRepairArticleSchedulerTest.java
Labels: 🛠️ feature

#97 [Feat] RestDocs에서 Security를 사용한다
  src/main/java/com/final_10aeat/domain/manager/controller/EmailController.java
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/global/security/jwt/JwtAuthenticationFilter.java
  src/test/java/com/final_10aeat/common/util/EntityUtil.java
  src/test/java/com/final_10aeat/common/util/admin/WithAdmin.java
  src/test/java/com/final_10aeat/common/util/admin/WithAdminSecurityContextFactory.java
  src/test/java/com/final_10aeat/common/util/manager/WithManager.java
  src/test/java/com/final_10aeat/common/util/manager/WithManagerSecurityContextFactory.java
  src/test/java/com/final_10aeat/common/util/member/WithMember.java
  src/test/java/com/final_10aeat/common/util/member/WithMemberSecurityContextFactory.java
  src/test/java/com/final_10aeat/docs/RestDocsSupport.java
  src/test/java/com/final_10aeat/domain/manager/docs/EmailControllerDocsTest.java
Labels: 👷‍♂️ fix, 🛠️ feature, 🚧 refactoring

#99 [Feature] 유지보수 게시글의 안건진행상황 등록, 수정을 구현한다.
  src/main/java/com/final_10aeat/domain/manager/controller/ManagerController.java
  src/main/java/com/final_10aeat/domain/repairArticle/controller/ManagerRepairArticleController.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/CreateCustomProgressRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/dto/request/UpdateCustomProgressRequestDto.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/CustomProgress.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/exception/CustomProgressNotFoundException.java
  src/main/java/com/final_10aeat/domain/repairArticle/repository/CustomProgressRepository.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerRepairArticleService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
Labels: 🛠️ feature

#101 [Test] 유지보수 게시글 관리 로직 REST Docs 문서화
  src/docs/asciidoc/email/email-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/repairarticle/repairarticle-api.adoc
  src/main/java/com/final_10aeat/common/enumclass/Progress.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/ManagerRepairArticleDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/unit/ManagerRepairArticleServiceTest.java
Labels: 🛠️ feature

#102 [Feature] 이슈 발행 기능을 구현한다.
  src/main/java/com/final_10aeat/common/exception/ArticleNotFoundException.java
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueController.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/ArticleIssuePublishRequestDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssue.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssueCheck.java
  src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueService.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleRepository.java
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberRegisterRequestDto.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
Labels: 🛠️ feature

#105 [Test] 이슈 발행 테스트코드 작성
  src/docs/asciidoc/articleissue/articleissue-api.adoc
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManagerArticleIssuePublishServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairArticleIssuePublishServiceTest.java
Labels: 🛠️ feature

#111 [Refactor] 회원가입시 Member에게 관리자 officeId 자동부여 구현
  src/main/java/com/final_10aeat/domain/member/dto/request/MemberRegisterRequestDto.java
  src/main/java/com/final_10aeat/domain/member/exception/MemberMissMatchException.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/domain/office/entity/Office.java
  src/main/java/com/final_10aeat/domain/repairArticle/entity/RepairArticle.java
  src/main/java/com/final_10aeat/domain/repairArticle/service/ManagerRepairArticleService.java
  src/test/java/com/final_10aeat/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/RegisterServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/WithdrawServiceTest.java
Labels: 🚧 refactoring

#113 [Feat] 관리자 정보 조회 구현
  src/docs/asciidoc/manager/manager-api.adoc
  src/main/java/com/final_10aeat/domain/manager/controller/ManagerController.java
  src/main/java/com/final_10aeat/domain/manager/dto/response/GetManagerResponseDto.java
  src/main/java/com/final_10aeat/domain/manager/entity/Manager.java
  src/main/java/com/final_10aeat/domain/manager/service/ManagerService.java
  src/test/java/com/final_10aeat/domain/manager/docs/ManagerControllerDocsTest.java
Labels: 🛠️ feature

#115 [Feature] 게시글 저장, 취소 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member/member-api.adoc
  src/docs/asciidoc/save/articlesave-api.adoc
  src/main/java/com/final_10aeat/domain/articleInteraction/entity/ArticleCheck.java
  src/main/java/com/final_10aeat/domain/save/controller/ArticleSaveController.java
  src/main/java/com/final_10aeat/domain/save/entity/ArticleSave.java
  src/main/java/com/final_10aeat/domain/save/exception/ArticleAlreadyLikedException.java
  src/main/java/com/final_10aeat/domain/save/exception/ArticleNotLikedException.java
  src/main/java/com/final_10aeat/domain/save/repository/ArticleSaveRepository.java
  src/main/java/com/final_10aeat/domain/save/service/ArticleSaveService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/save/docs/ArticleSaveControllerDocsTest.java
Labels: 🛠️ feature

#119 [Feat] 댓글 CRUD 기능 구현
  src/docs/asciidoc/comment/comment-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/final_10aeat/common/exception/UnexpectedPrincipalException.java
  src/main/java/com/final_10aeat/common/scheduler/DeleteCommentScheduler.java
  src/main/java/com/final_10aeat/domain/comment/controller/CommentController.java
  src/main/java/com/final_10aeat/domain/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/com/final_10aeat/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/com/final_10aeat/domain/comment/dto/request/UserIdAndRole.java
  src/main/java/com/final_10aeat/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/final_10aeat/domain/comment/entity/Comment.java
  src/main/java/com/final_10aeat/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/final_10aeat/domain/comment/exception/InvalidCommentDepthException.java
  src/main/java/com/final_10aeat/domain/comment/exception/ParentCommentNotFoundException.java
  src/main/java/com/final_10aeat/domain/comment/repository/CommentRepository.java
  src/main/java/com/final_10aeat/domain/comment/service/CommentService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/comment/docs/CommentControllerDocsTest.java
Labels: 🛠️ feature

#116 [Feat] 이슈 확인 기능을 구현한다.
  src/docs/asciidoc/articleissue/issuecheck-api.adoc
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueCheckController.java
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueController.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/request/ArticleIssueCheckRequestDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/request/ArticleIssuePublishRequestDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/dto/response/ArticleIssueCheckResponseDto.java
  src/main/java/com/final_10aeat/domain/articleIssue/entity/ArticleIssueCheck.java
  src/main/java/com/final_10aeat/domain/articleIssue/exception/IssueNotFoundException.java
  src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueCheckRepository.java
  src/main/java/com/final_10aeat/domain/articleIssue/repository/ArticleIssueRepository.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueCheckService.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueService.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueCheckControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManagerArticleIssuePublishServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairArticleIssuePublishServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueCheckServiceTest.java
Labels: 🛠️ feature

#121 [Fix] Admin 계정 생성 추가 및 리팩토링
  src/main/java/com/final_10aeat/domain/admin/controller/AdminController.java
  src/main/java/com/final_10aeat/domain/admin/dto/CreateAdminRequestDto.java
  src/main/java/com/final_10aeat/domain/admin/entity/Admin.java
  src/main/java/com/final_10aeat/domain/admin/service/AdminService.java
  src/main/java/com/final_10aeat/domain/manager/controller/ManagerController.java
  src/main/java/com/final_10aeat/domain/manager/service/ManagerService.java
  src/main/java/com/final_10aeat/domain/member/controller/MemberController.java
  src/main/java/com/final_10aeat/domain/member/dto/request/LoginRequestDto.java
  src/main/java/com/final_10aeat/domain/member/exception/PasswordMissMatchException.java
  src/main/java/com/final_10aeat/domain/member/service/MemberService.java
  src/main/java/com/final_10aeat/global/config/SecurityConfig.java
  src/main/java/com/final_10aeat/global/exception/ErrorCode.java
  src/test/java/com/final_10aeat/domain/manager/docs/ManagerControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manager/unit/ManagerServiceTest.java
  src/test/java/com/final_10aeat/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/member/unit/MemberServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/WithdrawServiceTest.java
Labels: 👷‍♂️ fix, 🛠️ feature, 🚧 refactoring

#124 [Fix] 실패하는 테스트 코드 수정
  src/test/java/com/final_10aeat/domain/manager/unit/ManagerServiceTest.java
  src/test/java/com/final_10aeat/domain/member/unit/MemberServiceTest.java
Labels: 👷‍♂️ fix

#125 [Test] 유지보수 게시글 조회 api REST Docs 문서화
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/repairarticle/get-repairarticle-api.adoc
  src/test/java/com/final_10aeat/domain/comment/docs/CommentControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/repairArticle/docs/OwnerRepairArticleDocsTest.java
Labels: 🛠️ feature

#122 [Feat] 이슈 상세조회 기능을 구현한다.
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueCheckController.java
  src/main/java/com/final_10aeat/domain/articleIssue/controller/ArticleIssueController.java
  src/main/java/com/final_10aeat/domain/articleIssue/service/ArticleIssueCheckService.java
  src/main/java/com/final_10aeat/global/config/RedisConfig.java
Labels: 🛠️ feature

#127 [Fix] test 코드 오류를 수정한다.
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueCheckServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueCheckServiceTest.java
Labels: 👷‍♂️ fix

#108 [Feat] 관리자는 유지관리 게시글을 작성,수정,삭제 할 수 있다
  src/main/java/com/final_10aeat/common/enumclass/ArticleCategory.java
  src/main/java/com/final_10aeat/common/enumclass/ManagePeriod.java
  src/main/java/com/final_10aeat/common/enumclass/MemberRole.java
  src/main/java/com/final_10aeat/common/enumclass/Progress.java
  src/main/java/com/final_10aeat/common/scheduler/DeleteManageArticleScheduler.java
  src/main/java/com/final_10aeat/domain/manageArticle/controller/ManagerManageArticleController.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/CreateManageArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/UpdateManageArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageArticleRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ManagerManageArticleService.java
Labels: 👷‍♂️ fix, 🛠️ feature

#129 [Test] 유지관리 게시글 관리자 기능 RestDocs & 테스트 코드
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/managearticle/manageArticle-api.adoc
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ManagerManageArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ManagerManageArticleServiceTest.java
Labels: 📕 document, 🛠️ feature

#128 [Test] 이슈 상세 조회 테스트 코드와 docs를 작성한다.
  src/docs/asciidoc/articleissue/issuecheckdetail-api.adoc
  src/test/java/com/final_10aeat/domain/issue/docs/ArticleIssueCheckControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/ManageIssueDetailServiceTest.java
  src/test/java/com/final_10aeat/domain/issue/unit/RepairIssueDetailServiceTest.java
Labels: 📕 document, 🛠️ feature

#132 [Refactor] 변경된 API명세서에 따라 법정점검 생성 코드 변경
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/CreateManageArticleRequestDto.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/ScheduleRequestDto.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/validator/ScheduleSizeMustBiggerThanZero.java
  src/main/java/com/final_10aeat/domain/manageArticle/dto/request/validator/ScheduleSizeValidator.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageArticle.java
  src/main/java/com/final_10aeat/domain/manageArticle/entity/ManageSchedule.java
  src/main/java/com/final_10aeat/domain/manageArticle/repository/ManageScheduleRepository.java
  src/main/java/com/final_10aeat/domain/manageArticle/service/ManagerManageArticleService.java
  src/test/java/com/final_10aeat/domain/manageArticle/docs/ManagerManageArticleControllerDocsTest.java
  src/test/java/com/final_10aeat/domain/manageArticle/unit/ManagerManageArticleServiceTest.java
Labels: 📕 document, 🚧 refactoring
